services:
app:
  image : webapp
  build:
    context: ./sit323_737-2023-t1-prac5p
    dockerfile: Dockerfile
  container_name: webapp_container
  restart: always
  ports:
    -"4026:3000 
    .+
    "
    healthcheck :
    test: ["CMD-","curl","-fail" http://localhost:3000/ || exit 1"]
    interval: 30s
    timeout : 10s
    retries : 3